name: HasegawaPhotos
favicon: null
layout_spectrum: 0.39268314046785235
typography_spectrum: 0.3499712322372943
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b9d5f9'
    - '#7da4e0'
    - '#121f3c'
    - '#1554b5'
    - '#973cf1'
  brandStrength: 0.5625
  lightness: 0.875
  saturation: 0.0625
  rhythmicContrast: 1
purpose: []
